<div class="service-detail padding-bottom justified">
    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-3">
            <?= $this->partial('serviceMenu', ['services' => $services]); ?>
        </div>
        <div class="col-xs-12 col-sm-9">
            <h1 class="general__title"><?= $services[$activeService] ?></h1>

            <div class="mt20 service-icon auction-icon"></div>

            <p class="mt20">Reposubasta es una división de Reality Realty, PSC que inició sus operaciones en el mes de agosto de 2014 con la primera gran subasta múltiple por cuatro sábados consecutivos en cuatro áreas regionales: Oeste en Mayagüez, Sur en Ponce, Este en Fajardo y Metro en San Juan. Este primer gran proyecto generó un éxito sin precedentes, logrando la venta de más del 40% del inventario.</p>
            <p class="mt20">Desde 2015 a la fecha se han trabajado doce (16) eventos, tres (3) cada año, en la zona metropolitana de San Juan, cuyos resultados promedio de forma consistente ha sido mayor de un 45% de inventario vendido.</p>
            <p class="mt20">Estos eventos son realizados “a viva voz”, se trabajan bajo la coordinación de un Líder de Proyecto y cuentan con un plan de mercadeo especializado de probada efectividad que incluye catálogo impreso, website, pautas en radio, TV y redes sociales, promoción digital, rotulación, días de “open house”, entre otros. De igual forma cuenta con un equipo gerencial y administrativo que asegura los aspectos operacionales necesarios para lograr los resultados y que incluye un Oficial de Cierres.
                En 2019 se creó la primera plataforma local de subasta de propiedades, Reposubasta Online, a través de la cual los licitadores pueden someter sus ofertas virtualmente.</p>

            <h3 class="mt40">Para más información, visita</h3>

            <a class="mt20" href="http://reposubasta.com" target="_blank">
                <img src="/img/repo.jpeg" width="200" />
            </a>
        </div>
    </div>
</div>
