<div class="service-detail padding-bottom justified">
    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-3">
            <?= $this->partial('serviceMenu', ['services' => $services]); ?>
        </div>
        <div class="col-xs-12 col-sm-9">
            <h1 class="general__title"><?= $services[$activeService] ?></h1>

            <div class="mt20 service-icon commercial-icon"></div>

            <p class="mt20">Nuestra División Comercial cuenta con una fuerza de ventas distribuida en todo Puerto Rico. Fue concebida como una de las principales aliadas del sector empresarial e institucional para sus necesidades de bienes raíces, ofreciendo al mercado corredores especializados en el área comercial en continua actualización de destrezas y conocimientos.</p>

            <div class="grey-bg">
                <h2 class="m0">Nuestros servicios están dirigidos a propietarios, instituciones bancarias, inversionistas y desarrolladores, siendo los principales los siguientes:</h2>

                <ul class="grey-bg-list">
                    <li>Venta y Arrendamiento de Propiedades Comerciales</li>
                    <li>Análisis del Mercado (BPO)</li>
                    <li>Representación de compradores / arrendatarios locales e internacionales</li>
                    <li>Inspección, Evaluación, Análisis y Clasificación de Portfolio de Propiedades</li>
                    <li>Short Sales Comerciales</li>
                </ul>
            </div>

            <p class="mt20">Contamos con una de las bases de datos de ventas comerciales más extensa de Puerto Rico lo que nos permite análisis y proyecciones precisas del mercado.</p>
        </div>
    </div>
</div>
