<div class="service-detail padding-bottom justified">
    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-3">
            <?= $this->partial('serviceMenu', ['services' => $services]); ?>
        </div>
        <div class="col-xs-12 col-sm-9">
            <h1 class="general__title"><?= $services[$activeService] ?></h1>

            <div class="mt20 service-icon consultoria-icon"></div>

            <p class="mt20">Las necesidades de nuestros clientes y el dinamismo de la industria han requerido reinventar los bienes raíces complementando la gestión de corretaje con la consultoría. Este equipo multidisciplinario está conformado por profesionales en las áreas de bienes raíces, finanzas, tasación, desarrollo, ingeniería, inversiones, entre otros, lo cual coloca a la compañía nuevamente a la vanguardia ofreciendo el valor añadido y el servicio especializado que demandan los nuevos tiempos.</p>

            <div class="grey-bg">
                <h2 class="m0">El alcance de estos servicios es adaptable y pueden ser tan simples o complejos según la necesidad del cliente. Como ejemplo podemos mencionar:</h2>

                <ul class="grey-bg-list">
                    <li>Aplicación de Metodología de Clasificación para Evaluación de Propiedades</li>
                    <li>Aplicación de Metodología "Projected Offer Net Proceed (PONP)"</li>
                    <li>Evaluación de Ofertas</li>
                    <li>"Automated Valuation Method System (AVM)"</li>
                    <li>BPO's y Evaluación de Carteras para Inversión</li>
                    <li>Análisis de Viabilidad de Proyectos</li>
                    <li>Gestoría y reactivación de premisos para desarrollos</li>
                    <li>Evaluación de Mercado por tipo de propiedad, zona geográfica, mejor uso o escenarios financieros.</li>
                </ul>
            </div>
        </div>
    </div>
</div>
