<div class="service-detail padding-bottom justified">
    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-3">
            <?= $this->partial('serviceMenu', ['services' => $services]); ?>
        </div>
        <div class="col-xs-12 col-sm-9">
            <h1 class="general__title"><?= $services[$activeService] ?></h1>

            <div class="mt20 service-icon education-icon"></div>

            <p class="mt20">Reality Realty cuenta con uno de los programas de adiestramiento más completos para sus corredores y la industria de bienes raíces en general a través de compañía hermana REIRE. A través del instituto se ofrecen los Cursos Preparatorios para la Licencia de Corredor y Vendedor de Bienes Raíces, Instructores, Adiestra- miento de Coaching Inicial, Bienes Raíces Comerciales, Inversiones entre otros temas de interés.</p>

            <h3 class="mt40">Para más información, visita</h3>

            <a class="mt20" href="https://reire.net" target="_blank">
                <img src="/img/reire.png" width="300" />
            </a>
        </div>
    </div>
</div>
