<div class="service-detail padding-bottom justified">
    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-3">
            <?= $this->partial('serviceMenu', ['services' => $services]); ?>
        </div>
        <div class="col-xs-12 col-sm-9">
            <h1 class="general__title"><?= $services[$activeService] ?></h1>

            <div class="mt20 service-icon newdevelopments-icon"></div>

            <p class="mt20">Nuestro Departamento de Proyectos Nuevos ofrece a la banca y al desarrollador de vivienda nueva una gama de servicios bajo un mismo techo. Desde el análisis del diseño inicial en los remanentes de terrenos ya desarrollados, diseño de la unidad de acuerdo a las necesidades del mercado actual, análisis de permisología existente, estudio del mercado y absorción hasta la preparación de la campaña publicitaria, ventas, mercadeo y la administración de las unidades residenciales durante el período de administración del desarrollador previo al traspaso de la misma a los Residentes.
                Actualmente manejamos varios Proyectos Nuevos tales como Harbour Lakes en Palmas del Mar, Villa Nueva Apartments en Caguas, Cabo Rojo, entre otros. De igual forma trabajamos el desarrollo de estrategias y la venta exitosa de otros proyectos en Guaynabo, Caguas y San Juan, entre los que podemos mencionar los siguientes:
            </p>

            <ul class="secondary-list">
                <li><a target="_blank" href="https://veredasdelmarpr.com/">Veredas del Mar</a></li>
                <li><a href="http://realityrealtypr.com/compra-venta/apartamento/puerto-rico/palmas-del-mar/harbour-lakes-palmas-del-mar/164860/">Harbour Lakes, Palmas Del Mar</a></li>
                <li>Gemini, Guaynabo</li>
                <li>Artesia Residences, Guaynabo</li>
                <li>Villas del Mar Beach Resort, Loíza</li>
                <li>Alturas de Santurce, San Juan</li>
                <li>Caguas Real, Caguas</li>
            </ul>

            <div class="grey-bg">
                <h2 class="m0">Nos especializamos en:</h2>

                <ul class="grey-bg-list">
                    <li>Análisis de Permisología: Verificamos el “status” de la permisología actual del proyecto y notificamos sobre los pasos siguientes y las agencias de gobierno a contactar. Desde la necesidad de renovación de permisos de construcción hasta la reactivación de permisos de usos.</li>
                    <li>Análisis de diseño: Contamos con ingenieros civiles y estructurales. Coordinación constante entre el desarrollador, banca interina, banca hipotecaria, contratista y comprador para el proceso de opción y compraventa de la unidad residencial.</li>
                    <li>Determinar el mejor uso de las fases no desarrolladas de la propiedad donde se construye el proyecto.</li>
                    <li>Evaluación histórica de las obras ya realizadas en el proyecto. Proyecciones futuras de las obras por realizarse.</li>
                    <li>Análisis de estrategias de mercadeo y ventas y recomendaciones sobre precio de venta, tipo de producto, facilidades vecinales disponibles, accesos y publicidad utilizada.</li>
                </ul>
            </div>
        </div>
    </div>
</div>
