<div class="service-detail padding-bottom justified">
    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-3">
            <?= $this->partial('serviceMenu', ['services' => $services]); ?>
        </div>
        <div class="col-xs-12 col-sm-9">
            <h1 class="general__title"><?= $services[$activeService] ?></h1>

            <div class="mt20 service-icon relocation-icon"></div>

            <p class="mt20">Reality Realty es la única compañía de Bienes Raíces en Puerto Rico que tiene un departamento completamente dedicado a ofrecer servicios de relocalización en y fuera de Puerto Rico. Como miembro de las redes de Compañías de Bienes Raíces más grandes a nivel mundial, tenemos la capacidad de ofrecerle EL MEJOR SERVICIO a nuestros clientes a la hora de planificar su relocalización en o fuera de Puerto Rico.</p>

            <div class="grey-bg">
                <h2 class="m0">Ofrecemos amplios servicios entre los cuales están incluídos:</h2>

                <ul class="grey-bg-list">
                    <li>Asistencia en el proceso de compra, venta o alquiler de propiedades a nuestros clientes que están siendo transferidos o están en proceso de relocalizarse en y fuera de Puerto Rico</li>
                    <li>Asistencia en la venta de propiedades localizadas en Puerto Rico de clientes que residen fuera de Puerto Rico</li>
                    <li>Asistencia en el proceso de búsqueda, venta y alquiler de propiedades a nivel global en y fuera de Puerto Rico</li>
                    <li>Orientación sobre el proceso de adquirir, vender o alquilar propiedades en o fuera de Puerto Rico</li>
                    <li>Orientación sobre el mercado de Bienes Raíces en Puerto Rico a individuos interesados en invertir en Puerto Rico entre otros.</li>
                </ul>
            </div>

            <p class="mt20">Nuestra compañía es la única representante de <a href="https://www.leadingre.com/" target="blank" style="text-decoration: none;"><strong>Leading Real Estate Companies of The World</strong></a> en Puerto Rico, red de bienes raíces que ofrece servicios multidimensionales a nivel local e internacional. Estos servicios abarcan los Estados Unidos y más de 55 países a través del mundo.
                El Departamento de Relocalización cuenta con profesionales con más de 15 años de experiencia en servicios de relocalización.</p>

            <center>                                    <a href="https://www.leadingre.com/" target="blank" style="text-decoration: none;">
                    <img src="https://www.leadingre.com/images/logos/lre_black_horiz_us_reg_2x.png" alt="Leading Real Estate Companies of the World" style="border: 0;width:200px;">
                </a>
            </center>
        </div>
    </div>
</div>
