<div class="grey padding-bottom justified">

    <div class="row padding-bottom margin-top">

        <div class="col-xs-12 col-sm-12">
            <p class="c23"><span class="c3">Nuestro equipo de reposeídas cuenta con una eficiente estructura administrativa para suplir todas las necesidades de bancos e inversionistas desde el análisis del inventario de propiedades, análisis de precio, evaluación bajo la metodología de clasificación por condición, localización y absorción, inspección y rotulación, mercadeo, showings, presentación de ofertas y contraofertas, evaluación periódicos de los resultados de las gestiones de mercadeo, informes ejecutivos y reportes requeridos. &nbsp; </span>
            </p>
            <p class="c23"><span class="c3">Reality Realty está comprometido a obtener el mejor precio en la venta, conforme a las condiciones del mercado, y establecer estrategias costo-efectivas &nbsp;para la rápida disposición de las propiedades. </span>
            </p>
        </div>
    </div>
</div>
