<div class="container grey padding-bottom justified">

    <div class="row margin-top">
        <div class="col-xs-12">
            <h3 class="grey">ÚNETE AL EQUIPO</h3>
        </div>
    </div>

    <div class="row padding-bottom margin-top">

        <div class="col-xs-12 col-sm-12">
            <span><strong>!Somos tu equipo de ventas!</strong></span>

            <p>Contamos con el equipo de trabajo más diestro de la industria, capaces de generar resultados que te benefician a ti.  ¡No esperes! Te serviremos con la misma ética y honestidad que nos ha llevado a ser una de las primeras firmas de bienes raíces en Puerto Rico.  Con Reality Realty estas en buenas manos.</p>

            <p>Te damos la bienvenida a nuestra gran familia de Reality Realty, en donde venderemos tu propiedad en tiempo récord.  Gracias por darnos la oportunidad de servirte.
Omayra Borges, CIPS, CRS, GRI, Presidente</p>
        </div>
        <div class="col-xs-12 col-sm-12">
            <span><strong>Reclutamiento</strong></span>

            <p>Una firma independiente realizó una encuesta entre las empresas más productivas de la nación americana, buscando cuáles eran los factores comunes que existían entre ellas para alcanzar el éxito que habían logrado.  Aparte de encuestar a los dueños y empleados, se encuestó a los agentes más productivos de cada firma y se le pregunto a cuál factor atribuían su éxito sin precedentes; el 50% de los agentes encuestados pasaban los $500,000 de ingresos por comisiones, y éstos contestaron que atribuían su éxito al “coaching”.</p>

            <p>Nosotros no reclutamos por reclutar, contamos con una primera fase de adiestramiento y luego con un coaching práctico para asegurarnos de que nuestros agentes comiencen preparados en todos los aspectos de bienes raíces.  Somos la compañía en Puerto Rico con mayor número de agentes designados en bienes raíces y de mayor producción por agente.  Por eso hacemos honor a nuestro lema “We have the best trained agents”.</p>

            <p></p>
        </div>
    </div>
</div>