<div class="container grey padding-bottom justified">

    <div class="row margin-top">
        <div class="col-xs-12">
            <h3 class="grey">ACT 22</h3>
        </div>
    </div>

    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-12">
            <strong>Purpose</strong>

            <br /><br />

            <p>
                Along with Act 20, Puerto Rico adopted the “Act to Promote the Relocation of Individual Investors” (Act 22) to stimulate economic development by offering nonresident individuals 100% tax exemptions on all interest, all dividends, and all long-term capital gains to entice nonresidents  to relocate in Puerto Rico.
            </p>

            <strong>Eligibility</strong>

            <br /><br />

            <p>
                Under the P.R. Internal Revenue Code: Nonresident individuals who become residents of Puerto Rico are considered eligible under Act 22 unless the individual was a resident of Puerto Rico at any time beginning on January 16, 1997 and ending on January 16, 2012.  An individual that becomes domiciled in Puerto Rico is considered a Puerto Rican resident. An individual’s 183-day physical presence in Puerto Rico establishes a presumption of residency under the Puerto Rico Tax Code.
            </p>

            <p>
                Under the U.S. Internal Revenue Code: Under U.S. IRC §933,income derived from sources within Puerto Rico by individuals qualified as bona fide residents are exempt from federal income taxation. For an individual to considered a bona fide resident of Puerto Rico under U.S. IRC §937, an individual must be present in Puerto Rico for at least 183 days of the year. Second, the individual must not have a tax home outside of Puerto Rico during the year. A tax home is determined to be located near an individual’s principle place of business. Third, the individual must have a closer connection to Puerto Rico than the U.S. or another country. This is determined by a variety of factors including but not limited to the location of individual’s home, family, personal belongings, and voting district.  The tax exemption period begins on the date an individual becomes a resident of Puerto Rico.
            </p>

            <strong>Tax Incentives</strong>

            <br /><br />

            <p>
                0% Taxes on Dividends and Interest: A qualified individual’s income from dividends and interest are exempt from Puerto Rico income taxes during the exemption period. A qualified individual is also exempt from U.S. federal income taxes if the revenue generated is considered Puerto Rico source income under U.S. IRC §933.
            </p>

            <p>
                0%-10% Taxes on Capital Gains: A qualified individual’s income from long-term capitals gains is exempt from Puerto Rico income taxes during the tax exemption period after the individual becomes a resident of Puerto Rico.  A qualified individual’s long-term capital gains prior to becoming a resident of Puerto Rico are subject to a 10% tax rate if realized within 10 years of residency or 5% if realized after 10 years of residency.
            </p>

            <p>
                Under U.S. law, long-term capital gains prior to becoming a bona fide resident of Puerto Rico that are realized within 10 years are subject to the provisions of U.S. IRC. If the long-term capital gains are realized after 10 years, the U.S. tax rate is 0%. Thus a bona fide resident would only be subject to the 5% Puerto Rico tax rate.
            </p>

            <p>
                <table border="1" cellspacing="2" cellpadding="2" width="100%">
                    <tbody>
                        <tr>
                            <td>
                                <p>Type of Income</p>
                            </td>
                            <td>
                                <p>P.R. Tax Rate</p>
                            </td>
                            <td>
                                <p>U.S. Tax Rate</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>Dividends and Interest</p>
                            </td>
                            <td>
                                <p>0%</p>
                            </td>
                            <td>
                                <p>0%</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>Long-term Capital Gains for new residents</p>
                            </td>
                            <td>
                                <p>0%</p>
                            </td>
                            <td>
                                <p>0%</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>Long-term Capital Gains prior to Residency; Realized <span class="aBn" data-term="goog_648319975" tabindex="0"><span class="aQJ">within 10 Years</span></span></p>
                            </td>
                            <td>
                                <p>10%</p>
                            </td>
                            <td>
                                <p>23.8%</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>Long-term Capital Gains prior to Residency; Realized after 10 Years</p>
                            </td>
                            <td>
                                <p>5%</p>
                            </td>
                            <td>
                                <p>0%</p>
                                <span class="HOEnZb">
                                    <font color="#888888">
                                        <div><br></div>
                                    </font>
                                </span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </p>

            <br />

            <p>
                <?= $this->partial('card', array('gerente' => $gerente)); ?>
            </p>
        </div>
    </div>
</div>