<?php
    $this->title = t('Recover your password');
?>
<div style='width:800px;margin: 0 auto'>

    <h1 class='title'> 
        <img src='/img/icons/login.png' />
        <?= $this->title; ?>
    </h1>

    <p>
        <?= t('Give us your email and we will send you an email with further instructions so you can recover your password.'); ?>
    </p>
            
    <!-- PASSWORD -->
    <div class='pretty-box' >
        <div class='pretty-box-header'>
            <?= t("Recover Password"); ?>
        </div>
        <div class='pretty-box-content'>
            <?= $Form->render(); ?>          
        </div>
    </div> 
    <!-- PASSWORD -->
                
</div>                
                


