<div class="row">
    <div class="col-xs-12 col-sm-9">
        <img src="/img/contactus.png" class="img-responsive"/>
    </div>
    <div class="col-xs-12 col-sm-3">
        <div>
            <h2>San Juan</h2>
            <p>1253 Ave. Fernandez Juncos,<br/>
                Esq. Roberto H. Todd, Pda. 18<br/>
                Santurce, PR</p>
            <a href="tel:(787) 745-8777">(787) 745-8777</a><br/>
            <a class="red-font" href="https://goo.gl/maps/fHLyT7zDBGm" target="_blank"><i
                    class="fas fa-map-marker-alt"></i> <?= t('translation1030') ?></a>
        </div>
        <div class="mt20">
            <h2>Caguas</h2>
            <p>Ave. Troche V-12<br/>Caguas, PR 00725</p>
            <a href="tel:(787) 745-8792">(787) 745-8792</a><br/>
            <a class="red-font" href="https://goo.gl/maps/fHLyT7zDBGm" target="_blank"><i
                    class="fas fa-map-marker-alt"></i> <?= t('translation1030') ?></a>
        </div>
    </div>
</div>
