<!DOCTYPE html>
<html>
<head>
    <base href="http://<?= $_SERVER['SERVER_NAME'] ?>/">
    <meta charset="utf-8">
    <title></title>
    <style>
        body {
            font-family: sans-serif;
        }
    </style>
</head>
<body style="margin:0;padding:0">
<div style="border-top: 1px solid #b1b1b1; border-bottom: 1px solid #B1B1B1">
    <table cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td width="20%" style="text-align:left;padding:5px;">
            </td>
            <td width="60%" align="center">
                <img src="https://s3.amazonaws.com/app-propiedades/flyer-logo.png" width="200"/>
            </td>
            <td width="20%" style="text-align:right;padding:5px;">
            </td>
        </tr>
    </table>
</div>

<div style="padding:10px;margin-top:20px;">

</div>
</body>
</html>
