<?php

/**
 * Account
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Account extends BaseAccount
{
    public function getFullName(){
        return $this->first_name." ".$this->last_name;
    }

    public function setPassword( $password ){
        $this->password_salt = Auth::salt();
        $this->password_hash = Auth::hash( $password , $this->password_salt );
    }

    public function isUsernameTaken( $username , $id = null ){
        $q = new Doctrine_Query();
        $q->from('Account');
        $q->select('id');
        $q->andWhere('username = ?' , $username );
        if( !empty( $id ) ) $q->andWhere('id <> ?', $id );
        $Account = $q->fetchOne();
        return $Account ? $Account->id : false;
    }

    public function isEmailTaken( $email , $id = null ){
        $q = new Doctrine_Query();
        $q->from('Account');
        $q->select('id');
        $q->andWhere('email LIKE ?' , $email );
        if( !empty( $id ) ) $q->andWhere('id <> ?' , $id );
        $Account = $q->fetchOne();
        return $Account ? $Account->id : false;
    }

    public function setActiveCompanyId($companyId){
        Session::delete('company_id');
        Session::write('company_id', $companyId);
    }

    public function getActiveCompany() {

        static $Company = null;

        if ($Company) {
            return $Company;
        }

        if (Session::read('company_id')) {
            return $Company = Doctrine::getTable('Company')->find(Session::read('company_id'));
        }

        //User is from a Company
        if ($this->company_id) {
            $Company = $this->Company;
        }
        //User is from an organization
        else {

            //Try to get first active company
            $Query = new Doctrine_Query();
            $Query->from('Company');
            $Query->andWhere('organization_id = ?', $this->organization_id);
            $Query->orderBy('is_active DESC');
            $Company = $Query->fetchOne();
        }

        Session::write('company_id', $Company->id);

        return $Company;
    }

    public function getAgency(){
        $agency = Session::read('agency');
        if($agency && $agency->id == Auth::get()->Organization->agency_id) return $agency;
        $Query = new Doctrine_Query();
        $Query->from('Agency a');
        $Query->select('a.name, a.subdomain, a.timezone, a.logo');
        $Query->andWhere('a.id = ?', Auth::get()->Organization->agency_id);
        $agency = $Query->fetchOne();

        Session::write('agency', $agency);
        return $agency;
    }

    public function getS3Photo() {
        if ($this->_data['s3_photo']) {
            return 'https://s3.amazonaws.com/app-propiedades/'.$this->_data['s3_photo'];
        }

        return '/new/logo_rr_black.svg';
    }

    public function getFormattedLandingHeader() {
        return 'https://s3.amazonaws.com/app-propiedades/'.$this->_data['landing_header'];
    }
}
