<?php

/**
 * Organization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Organization extends BaseOrganization
{
	public function getAdmin() {

        $q = new Doctrine_Query();
        $q->from('Account a');
        $q->innerJoin('a.Roles r');
        $q->andWhere('r.id = ?', 'organization.admin');
        $q->andWhere('a.organization_id = ?', $this->id);

        return $q->fetchOne();
    }
}