<?php

/**
 * Property
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Property extends BaseProperty
{
    public function getPhoto($index) {
       return $this->Photos[$index] ? $this->Photos[$index] : false;
    }

    public function getMainPhoto() {
        return $this->getPhoto(0);
    }

    public function getWatermark() {
        $watermark = 'https://s3.amazonaws.com/rrlistingsphotos/watermark/rr.png';

        if ($this->Category->type == 'Residential' && $this->sale_price >= 400000) {
            $watermark = 'https://s3.amazonaws.com/rrlistingsphotos/watermark/luxe.png';
        }

        return $watermark;
    }

    public function postUpdate($event)
    {
        parent::postUpdate($event);

        if ($this->isFieldModified('sale_price') || $this->isFieldModified('rent_price')) {
            $values = $this->toArray();
            $oldValues = array_merge($values, $this->getLastModified(true));

            $PropertyPriceLog = new PropertyPriceLog();
            $PropertyPriceLog->sale_price = $values['sale_price'];
            $PropertyPriceLog->old_sale_price = $oldValues['sale_price'];
            $PropertyPriceLog->rent_price = $values['rent_price'];
            $PropertyPriceLog->old_rent_price = $oldValues['rent_price'];
            $PropertyPriceLog->account_id = Auth::getId();
            $PropertyPriceLog->property_id = $this->id;
            $PropertyPriceLog->save();
        }
    }

    protected function isFieldModified($field)
    {
        $oldValues = array_merge($this->toArray(), $this->getLastModified(true));
        return $oldValues[$field] != $this[$field];
    }
}
