<?php

/**
 * PropertyPhoto
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PropertyPhoto extends BasePropertyPhoto
{
    function getThumborPhoto($size) {
        $url = 'https://d1lyw27hjbwoo4.cloudfront.net/';
        $watermark = $this->Property->getWatermark();
        $url .= "filters:watermark({$watermark},-20,-20,0,10)/";
        $url .= str_replace('https://s3.amazonaws.com/rrlistingsphotos/', '', $this->_data[$size]);
        return $url;
    }
}
