<div class="container grey padding-bottom justified">

    <div class="row margin-top">
        <div class="col-xs-12">
            <h3 class="grey">PR TAX INCENTIVES</h3>
        </div>
    </div>

    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-12">
            <p>
            <iframe src="https://player.vimeo.com/video/90028158" width="100%" height="562" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </p>

            <p>
            Moving to Puerto Rico has never been more attractive. The Caribbean island, which is part of the United States attracts thousands of new residents every year with near-perfect climate, an average temperature of 82&#8451;, miles of white sandy beaches, low cost of living, outstanding schools and healthcare services, and unlimited options for work, adventure and recreation. Now there is one more reason to move to Puerto Rico: 4% TAXES ON EXPORT SERVICES INCOME.
            </p>
        </div>
    </div>

    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-6">
            <strong>Export Services Act</strong>

            <p>
                <ul>
                    <li>
                        The Export Services Act (Act 20 of 2012) provides for <strong>4% maximum tax rate</strong> on <strong>income related to services</strong> for exportation provided by new Export Services businesses in Puerto Rico
                    </li>
                    <li>
                        Distributions from earnings and profits derived from the export services income such businesses are <strong>100% tax exempt</strong> for Puerto Rico residents
                    </li>
                    <li>
                        Qualifying companies will get a <strong>decree for 20 years</strong>, renewable for an additional 10 years, <strong>guaranteeing these rates</strong>
                    </li>
                    <li>
                        Puerto Rico corportations pay <strong>no federal taxes</strong> on Puerto Rico source income
                    </li>
                </ul>
            </p>
        </div>
        <div class="col-xs-12 col-sm-6">
            <strong>Quick Facts:</strong>

            <p>
                <ul>
                    <li>          
                        4% Corporate Tax Rate
                    </li>
                    <li>          
                        100% Tax-Exempt Dividends
                    </li>
                    <li>          
                        60% Exemption on Municipal Taxes
                    </li>
                    <li>           
                        20-year decree guaranteeing these rates
                    </li>
                    <li>          
                        No federal taxes on Puerto Rico source income
                    </li>
                </ul>
            </p>
        </div>
    </div>
    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-12">
            <strong>The Puerto Rico Advantage</strong>

            <br /><br />

            <p>
                <strong>Puerto Rico</strong> has long been known as an island paradise full of world-class beaches, natural wonders, golf, arts, shopping, dining and nightlife. And many also know of its reputation as a serious place <strong>committed to business</strong>, growth, development and <strong>low taxes</strong>; live and play in Puerto Rico is now. <strong>Make the comparison to your current situation</strong>. Move to Puerto Rico and <strong>bring your family and friends with you</strong>!
            </p>

            <br />

            <p>
                <?= $this->partial('card', array('gerente' => $gerente)); ?>
            </p>
        </div>
    </div>
</div>