<?php if( !empty($Contact['office_loc']) ): ?>
<div class="container-fluid contant-details nopadding">
	<div class="row mt mb">
		<div class="col-xs-12 col-sm-3">
			<?php if ( $Contact['user_foto'] ): ?>
	          <img src='<?= $Contact['user_foto'] ?>' class="img-responsive" />
	        <?php else: ?>
	          <img src='/img/no-avatar.jpg' class="img-responsive" />
	        <?php endif; ?>
		</div>	
		<div class="col-xs-12 col-sm-9">
			<div class="container-fluid nopadding">
				<div class="row">
					<div class="col-xs-3 col-sm-3">
						Agente:
					</div>
					<div class="col-xs-9 col-sm-9">
			           <strong><?= $Contact['user_firstname']; ?> <?= $Contact['user_lastname']; ?><?php if($Contact['user_lic']): ?>, Lic. <?= $Contact['user_lic']; ?><?php endif; ?></strong>
					</div>
				</div>

				<?php if($Contact['user_tel2']): ?>
				<div class="row">
					<div class="col-xs-3 col-sm-3">
						Móvil:
					</div>
					<div class="col-xs-9 col-sm-9">
						<strong><a href="tel:<?= $Contact['tel2']; ?>"><?= $Contact['user_tel2']; ?></a></strong>
					</div>
				</div>
				<?php endif ?>

				<div class="row">
					<div class="col-xs-3 col-sm-3">
			             Oficina:
					</div>
					<div class="col-xs-9 col-sm-9">
			            <strong><?= $Contact['office_loc']; ?></strong>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-3 col-sm-3">
						Teléfono:
					</div>
					<div class="col-xs-9 col-sm-9">
			           <strong><a href="tel:<?= $Contact['rbtel']; ?>"><?= $Contact['rbtel']; ?></a></strong>
					</div>
				</div>

				<?php if( !empty( $Contact['dir'])) : ?>
				<div class="row">
					<div class="col-xs-3 col-sm-3">
			             Dirección:
					</div>
					<div class="col-xs-9 col-sm-9">
			            <strong><?= $Contact['dir']; ?></strong>
					</div>
				</div>
				<?php endif; ?>	
			</div>
		</div>
	</div>
</div>
<?php endif ?>