<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
    
        <table width="700" border="0" cellspacing="0" cellpadding="0" align="center">
              <tr>
                <td style="font-family:Arial, Helvetica, sans-serif;font-size:14px;font-weight:bold" align="center">
                    <?= @$SUBJECT; ?>
                </td>
              </tr>
              <tr>
                <td>
                    <table width="99%" border="0" cellspacing="2" cellpadding="2" align="center">
                      <tr>
                        <td style=" border-right-width: 1px; border-left-width: 1px; border-right-style: solid; border-left-style: solid;   border-right-color: #086306; border-left-color: #086306;font-family:Arial, Helvetica, sans-serif;font-size:12px;">
                            <table width="97%" border="0" cellspacing="4" cellpadding="4" align="center" >
                              <tr>
                                <td><?= $this->getContent(); ?></td>
                              </tr>
                            </table>
                        </td>
                      </tr>
                    </table>
                </td>
            </tr>
        </table>
        <p>&nbsp;</p>
    </body>
</html>