<?php

$Javascript = helper('Javascript');
$Css = helper('Css');
$Flash = helper('Flash');
$ManagerMenu = helper('Menu', 'manager');

//Remove css
$Css->remove('/yammon/public/search/css/search.css');
$Css->remove('/yammon/public/table/css/table.css');
$Css->remove('/yammon/public/table/css/table-menu.css');
$Css->remove('/yammon/public/pagination/css/pagination.css');
$Css->remove('/yammon/public/dialog/css/dialog.css');
$Css->remove('/yammon/public/widget/dropdownlinks/dropdownlinks.css');
$Css->remove('/yammon/public/form/css/default.css');
$Css->remove('/yammon/public/form/css/button.css');


$ManagerMenu->add("category", array(
    "label" => t('Manager'),
    "class" => 'site-menu-category',
));
$ManagerMenu->add("accounts", array(
    "label" => t('Accounts'),
    "link" => "backend.company.accounts",
    "class" => 'site-menu-item',
    "icon" => "fa fa-user",
));
$ManagerMenu->add("categories", array(
    "label" => t('Property Categories'),
    "link" => "backend.company.settings.categories",
    'permission' => 'company.manage',
    "class" => 'site-menu-item',
    "icon" => "fa fa-home",
));
$ManagerMenu->add("entities", array(
    "label" => t('Entities'),
    "link" => "backend.company.settings.entities",
    'permission' => 'company.manage',
    "class" => 'site-menu-item',
    "icon" => "fa fa-building",
));
$ManagerMenu->add("production", array(
    "label" => t('Production Units'),
    "link" => "backend.company.settings.production",
    'permission' => 'company.manage',
    "class" => 'site-menu-item',
    "icon" => "fa fa-line-chart",
));

$ReportsMenu = helper('Menu', 'reports');
$ReportsMenu->add("category", array(
    "label" => t('Reports'),
    "class" => 'site-menu-category',
));
$ReportsMenu->add("production", array(
    "label" => t('Production'),
    "link" => "backend.company.reports.production",
    "class" => 'site-menu-item',
    "icon" => "fa fa-pie-chart",
));
$ReportsMenu->add("goals", array(
    "label" => t('By Goals'),
    "link" => "backend.company.reports.goals",
    "class" => 'site-menu-item',
    "icon" => "fa fa-pie-chart",
));
$ReportsMenu->add("byProductionUnit", array(
    "label" => t('By Units By Goals'),
    "link" => "backend.company.reports.byproductionunit",
    "class" => 'site-menu-item',
    "icon" => "fa fa-pie-chart",
));
?>
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="bootstrap admin template">
    <meta name="author" content="">
    <title><?= Configure::read('branding.name'); ?></title>

    <link rel="apple-touch-icon" href="<?= Configure::read('branding.favicon'); ?>">
    <link rel="shortcut icon" href="<?= Configure::read('branding.favicon'); ?>">
    <!-- Stylesheets -->
    <link rel="stylesheet" href="/global/css/bootstrap.min.css?v4.0.2">
    <link rel="stylesheet" href="/global/css/bootstrap-extend.min.css?v4.0.2">
    <link rel="stylesheet" href="/assets/css/site.min.css">
    <link rel="stylesheet" href="/css/custom.css">
    <link rel="stylesheet" href="/assets/skins/red.min.css">
    <!-- Plugins -->
    <link rel="stylesheet" href="/global/vendor/animsition/animsition.css">
    <link rel="stylesheet" href="/global/vendor/asscrollable/asScrollable.css">
    <link rel="stylesheet" href="/global/vendor/switchery/switchery.css">
    <link rel="stylesheet" href="/global/vendor/intro-js/introjs.css">
    <link rel="stylesheet" href="/global/vendor/slidepanel/slidePanel.css">
    <link rel="stylesheet" href="/global/vendor/flag-icon-css/flag-icon.css">
    <link rel="stylesheet" href="/global/vendor/waves/waves.css">
    <link rel="stylesheet" href="/global/vendor/morris/morris.min.css">
    <!-- Fonts -->
    <link rel="stylesheet" href="/global/fonts/material-design/material-design.min.css">
    <link rel="stylesheet" href="/global/fonts/brand-icons/brand-icons.min.css">
    <link rel="stylesheet" href="/global/fonts/font-awesome/font-awesome.css">
    <link rel="stylesheet" href="/global/fonts/glyphicons/glyphicons.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

    <!-- Plugins For This Page -->
    <link rel="stylesheet" href="/global/vendor/aspieprogress/asPieProgress.min.css?v4.0.2">

    <!-- Page -->
    <link rel="stylesheet" href="/assets/examples/css/charts/pie-progress.min.css?v4.0.2">

    <link rel="stylesheet" href="/assets/examples/css/dashboard/team.css?v4.0.2">

    <?= $Css->render(); ?>

    <!--[if lt IE 9]>
    <script src="/global/vendor/html5shiv/html5shiv.min.js"></script>
    <![endif]-->
    <!--[if lt IE 10]>
    <script src="/global/vendor/media-match/media.match.min.js"></script>
    <script src="/global/vendor/respond/respond.min.js"></script>
    <![endif]-->
    <!-- Scripts -->
    <script src="/global/vendor/breakpoints/breakpoints.js"></script>
    <script>
      Breakpoints();
    </script>
</head>
<body class="animsition">

<?= $this->getContent(); ?>

<!-- Core  -->
<script src="/global/vendor/babel-external-helpers/babel-external-helpers.js"></script>
<script src="/global/vendor/jquery/jquery.js"></script>
<script src="/global/vendor/tether/tether.js"></script>
<script src="/global/vendor/bootstrap/bootstrap.js"></script>
<script src="/global/vendor/animsition/animsition.js"></script>
<script src="/global/vendor/mousewheel/jquery.mousewheel.js"></script>
<script src="/global/vendor/asscrollbar/jquery-asScrollbar.js"></script>
<script src="/global/vendor/asscrollable/jquery-asScrollable.js"></script>
<script src="/global/vendor/ashoverscroll/jquery-asHoverScroll.js"></script>
<script src="/global/vendor/waves/waves.js"></script>
<!-- Plugins -->
<script src="/global/vendor/switchery/switchery.min.js"></script>
<script src="/global/vendor/intro-js/intro.js"></script>
<script src="/global/vendor/screenfull/screenfull.js"></script>
<script src="/global/vendor/slidepanel/jquery-slidePanel.js"></script>
<!-- Scripts -->
<script src="/global/js/State.js"></script>
<script src="/global/js/Component.js"></script>
<script src="/global/js/Plugin.js"></script>
<script src="/global/js/Base.js"></script>
<script src="/global/js/Config.js"></script>
<script src="/assets/js/Section/Menubar.js"></script>
<script src="/assets/js/Section/GridMenu.js"></script>
<script src="/assets/js/Section/Sidebar.js"></script>
<script src="/assets/js/Section/PageAside.js"></script>
<script src="/assets/js/Plugin/menu.js"></script>
<script src="/global/js/config/colors.js"></script>
<script src="/assets/js/config/tour.js"></script>
<script>
  Config.set('assets', '/assets');
</script>
<!-- Page -->
<script src="/assets/js/Site.js"></script>
<script src="/global/js/Plugin/asscrollable.js"></script>
<script src="/global/js/Plugin/slidepanel.js"></script>
<script src="/global/js/Plugin/switchery.js"></script>
<script src="/global/vendor/morris/morris.min.js"></script>
<script src="/global/vendor/raphael/raphael.min.js"></script>
<script src="/global/js/Plugin/switchery.min.js?v4.0.2"></script>
<script src="/global/vendor/aspieprogress/jquery-asPieProgress.js"></script>
<script src="/global/js/Plugin/aspieprogress.min.js?v4.0.2"></script>
<script src="/assets/examples/js/charts/pie-progress.min.js?v4.0.2"></script>
<script type="text/javascript">
  //Search Responsive
  jQuery('.yammon-search-modify').click(function (event) {
    event.preventDefault();

    jQuery('.yammon-search-modify-container').hide();
    jQuery('.yammon-search-advanced').slideDown(200);

  });
</script>
<script>
  (function (document, window, $) {
    'use strict';
    var Site = window.Site;
    $(document).ready(function () {
      Site.run();
    });
  })(document, window, jQuery);
</script>

<script>
  $.noConflict();
</script>

<?= $Javascript->render(); ?>
</body>
</html>
