<div class="container grey padding-bottom justified">

    <div class="row margin-top">
        <div class="col-xs-12">
            <h3 class="grey">ACT 20</h3>
        </div>
    </div>

    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-12">
            <strong>Purpose</strong>

            <br /><br />

            <p>
                Puerto Rico approved the “Law to Promote the Exportation of Services” (Act 20) in order to establish Puerto Rico as an international service center. Puerto Rico seeks to allure outside service entities via tax incentives to relocate to the island for the purposes of stimulating economic growth and social improvement. 
            </p>

            <strong>Eligibility</strong>

            <br /><br />

            <p>
                Act 20 applies to any entity with a bona fide establishment in Puerto Rico that is engaged in an eligible service for export. Eligible services include but are not limited to: investment banking and other financial services, research and development, advertising and public relations, consulting, electronic programming development, call centers, professional services, and centralized management services. An eligible service must also qualify as an export service. An eligible service done by a foreign entity or non-resident individual that does not relate to business activities within Puerto Rico qualifies as an export service.
            </p>

            <p>
                An eligible service provider is required to obtain a Tax Exemption Decree that will endure for a term of 20 years and may be renewed for an additional 10 years. The Tax Exemption Decree constitutes a contract between the service provider and the Puerto Rican Government that is immune to any future legislation.
            </p>

            <strong>Tax Incentives</strong>

            <br /><br />

            <p>
                These lucrative tax incentives apply to all new Puerto Rican businesses under a Tax Exemption Decree:
            </p>

            <p>
                <ul>
                    <li>
                        0% Taxes on Earnings and Profit: The exemption includes a 100% tax exemption of earning and profit distributions on income generated from export services.
                    </li>
                    <li>
                        3-4% Flat Income Tax: A 4% flat income tax rate on income generated from export services, or a 3% tax when more than 90% of an service provider’s gross income is from export services.
                    </li>
                    <li>
                        0% Property Tax: 100% property tax exemption for the initial 5 years of operation for certain export services including corporate headquarters, call centers, shared service centers for accounting, finance, marketing, human resources, and other centralized management services. After the 5-year period expires, a 90% tax exemption will apply for the remainder of the Tax Exemption Decree.
                    </li>
                </ul>
            </p>

            <br />

            <p>
                <?= $this->partial('card', array('gerente' => $gerente)); ?>
            </p>
        </div>
    </div>
</div>