<?= $Search->render(); ?>

<?php if(Auth::hasPermission('organization:company.manage')): ?>
<div class="actions">
    <div class="row">
        <div class="col-xs-12">
            <a class="btn btn-success btn-sm" href="<?= url('.edit') ?>"><i class="fa fa-plus"></i>&nbsp;&nbsp;<?= t('Add New Company') ?></a>
        </div>
    </div>
</div>
<?php endif ?>

<div class="well well-sm hidden-xs mt20">
    <div class="row">
        <div class="col-sm-2"><i class="fa fa-users"></i> Accounts</div>
        <div class="col-sm-2"><i class="fa fa-bullhorn"></i> Campaigns</div>
        <div class="col-sm-2"><i class="fa fa-bullseye"></i> Sources</div>
        <div class="col-sm-3"># Phone numbers</div>
        <div class="col-sm-3">@ Email addresses</div>
    </div>
</div>


<?= $Table->render(); ?>
