<?php
$Section = helper("Section");

Configure::write("seo.title", t('translation116'));
?>

<style type="text/css">

    .broker-info .photo {
        float: left;
        width: 110px;
        margin-left: 20px;
    }

    .broker-info .bar {
        clear: both;
    }

    .broker-info .info1 {
        float: left;
        width: 270px;
    }

    .broker-info .info2 {
        float: left;
        width: 220px;
        margin-left: 30px;
    }

    table.styled {
        margin: 0px;
        font-size: 11px;
    }

    table.styled th {
        width: 25%;
        padding: 2px;
    }

    table.styled td {
        width: 75%;
        padding: 2px;
    }

    #content-inner {
        padding: 10px 0px;
    }

    .agent {
        width: 250px;
        margin: 0 auto 60px auto;
        padding: 0 20px 20px 20px;
        min-height: 500px;
        position: relative;
        border: 1px solid #EFEFEF;
    }

    .agent-image {
        margin: 0 -20px 10px -20px;
        overflow: hidden;
    }

    .buttons {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        padding: 20px;
    }

    .buttons .btn {
        width: 100%
    }

    .buttons .normalBtn {
        color: white;
    }

    .search-agents {
        padding: 30px 10px;
        margin-bottom: 20px;
    }

    .search-agents .btn {
        width: 100%;
    }

</style>

<div class="search-agents shadowBottom">
    <div class="container">
        <form id="searchForm" action="" method="get" name="search" class="searchForm form form-horizontal">
            <input type="hidden" value="<?= $type ?>" name="type" />
            <div id="searchFilterTable">
                <div class="row">
                    <div class="col-xs-12 col-sm-3">
                        <input name="search[firstname]" type="text" value="<?= @$searchFilter['firstname'] ?>"
                               class="searchField useDefault" rel="<?= t('translation132') ?>"
                               placeholder="<?= t('translation132') ?>"/>
                    </div>

                    <div class="col-xs-12 col-sm-3">
                        <select name="search[service]">
                            <option value=""><?= t('translation135') ?></option>
                            <?php foreach ($services as $value => $service): ?>
                                <option <?php if ($value == @$searchFilter['service']): ?>selected<?php endif ?>
                                        value="<?= $value ?>">
                                    <?= $service ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>

                    <div class="col-xs-12 col-sm-3">
                        <button type="submit" class="btn normalBtn button positive submitBtn"><?= t('translation129') ?></button>
                    </div>

                    <div class="col-xs-12 col-sm-3">
                        <a class="btn btn-default" href="?"><?= t('translation141') ?></a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="container">

    <ol class="breadcrumb list-breadcrumb">
        <li><a href="<?= url('/') ?>"><?= t('translation321') ?></a></li>
        <li class="active"><?= t('translation348') ?></li>
    </ol>

    <div id="content" class="below mt40">
        <div class="">
            <div class="row">
                <?php $i = 1;
                $last = count($Brokers);
                foreach ($Brokers

                as $key => $Agent) : ?>
                <div class="col-xs-12 col-sm-3 result result-<?php echo ($key % 4) ? 'odd' : 'even' ?>">
                    <div class="agent">
                        <div class="agent-image">
                            <?php if ($Agent->_data['s3_photo']): ?>
                                <img src='<?= $Agent['s3_photo'] ?>' class="img-responsive"/>
                            <?php else: ?>
                                <div style="height: 248px; width: 248px; padding: 100px 30px; opacity: .5;">
                                    <img src='<?= $Agent['s3_photo'] ?>' class="img-responsive"/>
                                </div>
                            <?php endif; ?>
                            <?php if ($Agent->is_top_agent) : ?>
                                <img class="top-agent" src="/img/top.png" />
                            <?php endif; ?>
                        </div>
                        <div>
                            <h3><?= $Agent['first_name'] ?> <?= $Agent['last_name'] ?></h3>
                            <strong>
                                <small><?= $Agent['position'] ?></small>
                            </strong><br/>
                            <?php if ($Agent['license']): ?>
                                <small><?= t('Lic.') ?> <?= htmlentities($Agent['license']) ?></small>
                            <?php endif; ?>
                        </div>
                        <div class="mt5 clearfix">
                            <div class="pull-left">
                                <small><strong><?= t('translation334'); ?>:</strong></small><br/>
                                <?php if ($Agent->commercial): ?>
                                    <span><?= t('translation336') ?></span><br/>
                                <?php endif ?>
                                <?php if ($Agent->resell): ?>
                                    <span><?= t('translation5') ?></span><br/>
                                <?php endif ?>
                                <?php if ($Agent->relocation): ?>
                                    <span><?= t('translation338') ?></span><br/>
                                <?php endif ?>
                            </div>
                            <div class="pull-right">
                                <small><strong><?= t('translation137'); ?>:</strong></small><br/>
                                <?= htmlentities($Agent['phone']) ?>
                            </div>
                        </div>

                        <div class="buttons">
                            <?php if (count($Agent['Properties']) > 0 || AccountTable::secoundById($Agent['id'])): ?>
                                <a class="btn btn-default normalBtnWhite" href='/propiedades?search[user_id]=<?= $Agent['id'] ?>'><?= t('translation140'); ?> <?= $Agent['first_name'] ?> </a>
                            <?php endif; ?>
                            <a class="mt5 btn btn-default normalBtn" href='/contactenos?broker_id=<?= $Agent['id'] ?>'><?= t('translation347'); ?></a>
                        </div>
                    </div>
                </div>

                <?php if ($i == $last): ?>
            </div>
            <?php elseif ($i % 4 == 0): ?>
        </div>
        <div class="row">
            <?php endif ?>

            <?php $i++; ?>

            <?php endforeach; ?>
        </div>

        <div class="row">
            <div class="pull-right col-xs-12">
                <div class="paginationContainer text-center">
                    <?php echo $Pagination->render() ?>
                </div>
            </div>
        </div>

    </div>

</div>
</div>
