<div class="container grey padding-bottom">
    <div class="row">
        <div class="col-xs-12 text-center">
            <h3 class="grey">Nuestros estudios demuestran que:</h3>
        </div>
    </div>

    <div class="row margin-top">
        <div class="col-xs-12 text-center">

            <p>En promedio, sólo el 33% de las propiedades listadas en Puerto Rico son vendidas.</p>

            <span class="highlight"><strong>¡En Reality Realty el 75% de las propiedades listadas son vendidas! </strong></span>

            <p>En promedio, sólo el 50% de las propiedades en Puerto Rico son vendidas a su precio original.</p>

            <span class="highlight"><strong>¡En Reality Realty el 87% de las propiedades lograr venderse a precio original!</strong></span>

            <p>Una propiedad en Puerto Rico tarda de 90 a 120 días aproximadamente en ser vendida.</p>

            <span class="highlight"><strong>¡En Reality Realty el promedio para vender una propiedad de 45 a 60 días solamente!</strong></span>
            </br />
            <span class="highlight"><strong>¡Te puedes ahorrar más de la mitad del tiempo! </strong></span>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="spacer"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h3 class="grey">¿CÓMO LO LOGRAMOS?</h3>
            <strong class="style12">La diferencia está en nuestros agentes. </strong>
        </div>
    </div>

    <div class="row padding-bottom margin-top justified">

        <div class="col-xs-12 col-sm-12">
             Reality Realty cuenta con el equipo de agentes mejor preparado de toda la industria de bienes raíces en Puerto Rico, adiestrados para lograr vender tu propiedad, a su precio original, en tiempo récord.</span>

            <p><strong>Esto es posible por 5 razones : </strong></p>

            <ol>
                <li>
                    Nuestros agentes conocen y dominan las técnicas de persuasión, negociación y ventas necesarias para vender tu propiedad en tiempo récord
                </li>
                <li>
                    Nuestros agentes ponen los intereses del cliente primero, a manera de proteger lo mas preciado para ti: tu inversión
                </li>
                <li>
                    Nuestros agentes poseen un amplio conocimiento de mercado, por lo tanto, puedes confiar en la señoría que recibirás y en a excelencia de su servicio. En palabras sencillas: con un agente de Reality Realty está buenas manos.
                </li>
                <li>
                    Nuestros agentes laboran junto a un excelente equipo de profesionales para ofrecerte el servicio “One Stop Shop”. Con este servicio, único de <strong>Reality Realty,</strong> abogados, contadores, ingenieros, tasadores y agrimensores te asisten en el proceso de compraventa de tu propiedad. ¡Todo esto bajo un mismo techo!
                </li>
                <li>
                    Nuestros agentes son reconocidos por su compromiso, dinamismo, entrega y honradez. La filosofía de los agentes de <strong>Reality Realty</strong> es: sobrepasar las expectativas del cliente con un servicio de altura que se traduzca en resultados.
                </li>
            </ol>
        </div>
        <div class="col-xs-12 col-sm-12">
            <p>En Reality Realty estamos para servirte, ya sea que quieras adquirir una propiedad, vender la que posees o simplemente buscas orientación en cuanto a compra, venta o alquiler. Contamos con 15 años de experiencia en el campo de las Bienes Raíces y nuestro equipo es el mejor adiestrado en la isla.</p>


            <p>En Reality Realty contamos con distintos departamentos que se ajustan a las necesidades de nuestros clientes, creemos que un trato personalizado y segmentado de acuerdo a los intereses de nuestros clientes, es la clave para ofrecer un servicio de excelencia y que se ajuste a cada necesidad.</p>
        </div>
    </div>
</div>