<div class="container grey padding-bottom testimonials justified">

    <div class="row margin-top">
        <div class="col-xs-12">
            <h3 class="grey">TESTIMONIOS</h3>
        </div>
    </div>

    <div class="row padding-bottom margin-top">

        <div class="col-xs-12 col-sm-6 same-heigth">
            <div class="padding-bottom">
                <span><strong>Propiedad Comercial: Doble Seis, Gurabo</strong></span>

                <p>Definitivamente volvería a utilizar los servicios de Erick J. Bracero Serrano de Reality Realty, PSC. Siempre me mantuvo informada, siempre devolvía mis llamadas rápidamente. ¡Su servicio al cliente y profesionalismo es excelente! ¡Lo recomiendo 100%!</p>

                <p><strong>Normarie Hernández</strong></p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 same-heigth">
            <div class="padding-bottom">
                <span><strong>Proyectos Nuevos: Art at San Patricio</strong></span>

                <p>Por este medio deseo agradecer a su PN Manager, Sr. Erick J. Bracero, por la cortesia y profesionalismo con que fuimos tratados en Art San Patricio.  Agradecemos sinceramente el trabajo del Sr. Bracero.  Tambien deseo felicitarles a ustedes por tener empleados de esta categoria.</p>
                
                <p>Agradezco, ademas, a la Srta. Margarita Garrastegui, vendedora, por la cortesia y calor humano con que fuimos tratados.</p>
     
                <p>Les deseo mucho exito en sus funciones.</p>
        
                <p>Atentamente,</p>

                <p><strong>Maria del Rio<br />Hato Rey, PR</strong></p>
            </div>
        </div>
    </div>

    <div class="row padding-bottom margin-top">

        <div class="col-xs-12 col-sm-6 same-heigth">
            <div class="padding-bottom">
                <span><strong>Reventa: Cond. Valle Santa Cecilia</strong></span>

                <p>Estoy muy contenta y agradecida con el servicio de Alexis de Reality Realty, en la compra de mi Apartamento en el Condominio Valle Santa Cecilia en Caguas.</p>

                <p>Alexis me ayudo mucho y puedo decir que es una persona amable y servicial.</p>

                <p>Gracias Reality Realty!</p>

                <p><strong>Lilliana Acosta</strong></p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 same-heigth">
            <div class="padding-bottom">
                <span><strong>Reventa</strong></span>

                <p>Por este medio, deseo agradecer al Sr. Alexis Rodriguez, por su esfuerzo y dedicación para lograr la venta de mi propiedad en tiempo record.</p>

                <p><strong>Jose Rivera</strong></p>
            </div>
        </div>
    </div>
</div>