<div class="panel">
    <div class="panel-body container-fluid">
		<?= $Search->render(); ?>
	</div>
</div>


<div class="panel">
    <div class="panel-body container-fluid">
        <a class="btn btn-success btn-sm" href="<?= url('.edit') ?>"><i class="fa fa-plus"></i>&nbsp;&nbsp;<?= t('Add New Account') ?></a>
        <a class="btn btn-default btn-sm " href="<?= url('.branches') ?>"><i class="fa fa-building"></i>&nbsp;&nbsp;<?= t('Manage Branches') ?></a>
    </div>
</div>

<div class="panel">
    <div class="panel-body container-fluid">
		<?= $Table->render(); ?>
	</div>
</div>
