<?php if (count($Properties)): ?>
<div class="container container-main-padding list-container">
    <div class="results">
        <div class="row">
            <?php
            $i = 1;
            $last = count($Properties);
            foreach ($Properties

            as $Property):
            ?>

            <?php
            //$prices = PropertyTable::priceLog($Property->id);
            $rebajada = false;
            ?>

            <div class="col-xs-12 col-sm-4 result result-<?php echo ($i % 2) ? 'even' : 'odd' ?>">
                <?= $this->partial('property', compact('Property')); ?>
            </div>

            <?php if ($i == $last): ?>
        </div>
        <?php elseif ($i % 3 == 0): ?>
    </div>
    <div class="row">
        <?php endif ?>

        <?php $i++; ?>

        <?php endforeach; ?>
    </div>
    <?php endif ?>

    <?php if (isset($Pagination)): ?>
    <div class="paginationContainer text-center">
        <?php echo $Pagination->render() ?>
    </div>
    <?php endif ?>
</div>
