<?= $Search->render(); ?>

<br />

<div class="well well-sm">
    <div class="row">
        <div class="col-sm-2"><i class="fa fa-users"></i> Accounts</div>
        <div class="col-sm-2"><i class="fa fa-bullhorn"></i> Campaigns</div>
        <div class="col-sm-2"><i class="fa fa-bullseye"></i> Sources</div>
        <div class="col-sm-3"># Phone numbers</div>
        <div class="col-sm-3">@ Email addresses</div>
    </div>
</div>

<?= $Table->render(); ?>
