<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            MEMO's
        </h3>
    </div>
    <div class="panel-body container-fluid">
            <?php foreach($DocumentCategories as $ParentCategory): ?>
                    <?php foreach($ParentCategory->Childs as $DocumentCategory): ?>
                        <span><?= $DocumentCategory->name ?></span>
                        <ul>
                            <?php foreach($DocumentCategory->Documents as $Document): ?>
                                <li>
                                    <a target="_blank" href="https://s3.amazonaws.com/app-propiedades/<?= $Document->path ?>"><?= $Document->name ?></a>

                                    <?php if(Auth::hasPermission('document.manage')): ?>
                                        <a style="color: black; margin-left: 15px;" href="<?= url('.edit?id='.$Document->id) ?>">Edit</a> | <a style="color: black; margin-left: 15px;" onclick="return confirm('Are you sure?')" href="<?= url('.delete?id='.$Document->id) ?>">Delete</a>
                                    <?php endif ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endforeach; ?>
            <?php endforeach; ?>
    </div>
</div>
