<?php
    $Section    = helper("Section");

    define('DISABLE_GLOBAL_CONTACT_FORM', true);
?>

<!-- TOP CONTENT -->
<div class="container mt20 grey padding-bottom">

    <ol class="breadcrumb realty-breadcrumb">
        <li><a href="<?= url('/') ?>"><?= t('translation321') ?></a></li>
        <li class="active"><?= t('translation1004') ?></li>
    </ol>
<!-- MAIN CONTENT -->
    <div id="content" class="below margin-top">

        <?= $this->partial('contact'); ?>

        <div class="row mt40">
            <div class="col-xs-12 col-sm-12">
                  <h3><?= t('translation25'); ?></h3>

                  <form action="/contactenos" method="post" class="contact mt20 form form-horizontal" id="contactForm">

                    <div class="row padding-bottom">
                        <div class="col-xs-12 col-sm-6">
                            <div class="">
                                <label for='name'><?= t('translation132'); ?></label>
                                <input type="text" class='contactField name' name='var1' value="" />
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <div class="">
                                <label for='phone'><?= t('translation29'); ?></label>
                                <input type="text" class='contactField phone' name='var2' value="" />
                            </div>
                        </div>
                    </div>

                    <div class="row padding-bottom">
                        <div class="col-xs-12 col-sm-6">
                            <div class="">
                                <label for='mail'>Email</label>

                                <div style='display:none'>
                                    <input name='email' value="" />
                                </div>
                                <input type="text" class='contactField mail' name='var3' />
                            </div>

                            <div class="margin-top hidden-xs"></div>

                            <div>
                                <?php if($broker): ?>
                                    <input type="hidden" value="<?= $broker->id ?>" name="broker_id" />

                                    <label for="chkMetro" class=""><?= t('translation261'); ?></label>

                                    <input type="text" class='contactField agent' name='agente' value="<?= $broker->getFullName() ?>" readonly />
                                <?php endif ?>
                            </div>

                            <div class="margin-top hidden-xs"></div>
                        </div>
                        <div class="col-xs-12 col-sm-6">
                            <div class="">
                                <label><?= t('translation266'); ?></label>
                                <textarea class='contactField msg' name='var4' rows="6"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row padding-bottom">
                        <div class="col-xs-12">
                            <div class="text-center">
                                <input type="submit" class="normalBtn" value="<?= t('translation32'); ?>" />
                            </div>
                        </div>
                    </div>

                  </form>
            </div>
        </div>
    </div>
</div>

<?= $Section->start("javascriptFooter"); ?>
<?= $Section->render("javascriptFooter"); ?>

<script type="text/javascript">

jQuery(document).ready(function(){

    jQuery('#contactForm').bind('submit.contactForm', function() {
        sendContactForm('main' , jQuery(this) );
        return false;
    });

});

</script>

<?= $Section->end(); ?>
