<div class="container grey padding-bottom justified">

    <div class="row padding-bottom margin-top">

        <div class="col-xs-12 col-sm-8">

            <img src="/img/plus.png" width="150" />

            <br /><br />

            <strong style="color:#ee1c24">REALITY PLUS</strong>

            <p>Es un conjunto de programas de formación dirigidos a elevar el estandar profesional de nuestros corredores. R+ es una marca de Reality Realty (RR).</p>

            <br />

            <strong>Llega a otro nivel!</strong>

            <br />
            <br />

            <strong style="color:#ee1c24">REALITY PLUS</strong>

            <p>Cuenta con 5 certificaciones en su primera etapa, las mismas se desarrollarán de modo presencial y contará con el sistema de Aula Virtual, donde encontrarás los contenidos por programa, espacios de interacción, biblioteca virtual, anuncios y noticias del sector.</p>
            <br />

            <p>PROGRAMAS:</p>

            <img src="/img/programas.png" width="350px" />
        </div>
        <div class="col-xs-12 col-sm-4 hidden-xs">
            <div style="background:#ee1c24 url('/img/side.png') bottom right no-repeat;height:570px;width:251px">
            </div>
        </div>
    </div>
</div>