<?php

    global $PARTNER_KEY;

    $this->title = t('Recover your password');
    $link = url( 'account.password.recover?p='.$PARTNER_KEY.'&key='.$key );

?>
<h1 style="font-weight:bold;font-size:2em;margin:.5em 0;">
    <?= t('Hello, %0,' , $name); ?>
</h1> 

<p>
    <?= t("Thanks, you are almost done. For security purposes we need you to verify your email by cliking on the button bellow or entering
    the code specified below on our site."); ?>
</p>
            
<div style='text-align:center'>

    
    <strong>
        <?= t('To recover your password click on this button:'); ?>	    
    </strong>

    <br />
    <br />
    
    <a href='<?= $link;?>' style='display: block; text-decoration: none; width:200px; margin:0 auto;border:solid #3b6e22 1px; border-bottom:solid #2c5115 1px; cursor:pointer; -moz-border-radius: 4px; -webkit-border-radius: 4px ; border-radius: 4px'>
        <span style='display: block; padding:6px 0 6px 0; background-color:#68a64c; border-top:solid #98c286 1px; text-align:center; color:#ffffff; -moz-border-radius: 4px; -webkit-border-radius: 4px ; border-radius: 4px'>
            <?= t("Recover Password"); ?>
        </span>
    </a>
    
    <br />
    <br />        
        
    <strong>
        <?= t("or you can visit this link"); ?> <br />
        <a href='<?= $link; ?>'> <?= $link; ?> </a>	    
    </strong>        	
    
</div>    
