<?php

$this->classes = 'page-forgot-password layout-full';

?>

<!-- Page -->
  <div class="page vertical-align text-xs-center" data-animsition-in="fade-in" data-animsition-out="fade-out">
    <div class="page-content vertical-align-middle">
        <?= $Flash ?>

      <h2>Forgot Your Password ?</h2>
      <p>Input your registered email to reset your password</p>

      <?php if( $errors = $Form->getErrors() ): ?>
        <?php foreach( $errors as $error ): ?>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Oh snap!</strong> <?= $error ?>
            </div>
        <?php endforeach ?>
    <?php endif; ?>

      <form method="post" role="form" autocomplete="off">
        <div class="form-group form-material floating" data-plugin="formMaterial">
          <input type="email" class="form-control empty" id="inputEmail" name="Form[email]" value="<?= $Form->get('email')->getValue(); ?>">
          <label class="floating-label" for="inputEmail">Your Email</label>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">Reset Your Password</button>
        </div>
      </form>
    </div>
  </div>
  <!-- End Page -->
