<style>
    .broker-image {
        width: 200px;
        height: 200px;
        overflow: hidden;
        text-align: center;
        margin: 0 auto;
        position: relative;
    }

    .broker-image .mainImage {
        width: 200px;
    }

    .contant-details h4 {
        margin: 0;
    }

    .top-agent {
        width: 120px !important;
        left: -5px;
    }
</style>

<div class="container-fluid contant-details mt40  text-center">
    <div class="row mt mb">
        <div class="col-xs-12 col-sm-12  text-center">
            <div class="broker-image">
                <?php if ( $Contact->s3_photo ): ?>
                    <img class="mainImage" src='<?= $Contact->s3_photo ?>' />
                <?php else: ?>
                    <img class="mainImage" src='/img/no-avatar.jpg' class="img-responsive" />
                <?php endif; ?>
            </div>
            <?php if ($Contact->is_top_agent) : ?>
                <img class="top-agent" src="/img/top.png" />
            <?php endif; ?>
        </div>
    </div>
	<div class="row mt mb mt20">
		<div class="col-xs-12 col-sm-12">
			<div class="container-fluid nopadding">
				<div class="row">
					<div class="col-xs-12">
			           <h4><?= $Contact->getFullName() ?></h4>
                        <small><?php if($Contact->license): ?>Lic. <?= $Contact->license; ?><?php endif; ?></small>
					</div>
				</div>

                <?php if($Contact->phone): ?>
				<div class="row">
					<div class="col-xs-12">
						<?= t('translation1050'); ?>: <a href="tel:<?= $Contact->phone ?>"><?= decorator('phone', $Contact->phone) ?></a>
					</div>
				</div>
				<?php endif ?>

				<div class="row">
					<div class="col-xs-12">
                        <?= t('translation1051'); ?>: <?php if($Property->sale_price && round($Property->sale_price) >= 450000): ?><a href="tel:7874183020"> (787) 418-3020</a><?php else: ?><a href="tel:<?= $Contact->Branch->phone; ?>"><?= decorator('phone', $Contact->Branch->phone) ?></a><?php endif ?>
					</div>
				</div>

                <?php if($SecondaryAgent): ?>
                    <br /><hr /><br />
                    <div class="row">
                        <div class="col-xs-12">
                            <h4><?= $SecondaryAgent->getFullName() ?></h4>
                            <small><?php if($SecondaryAgent->license): ?>Lic. <?= $SecondaryAgent->license; ?><?php endif; ?></small>
                        </div>
                    </div>

                    <?php if($SecondaryAgent->phone): ?>
                        <div class="row">
                            <div class="col-xs-12">
                                <?= t('translation1050'); ?>: <a href="tel:<?= $SecondaryAgent->phone ?>"><?= decorator('phone', $SecondaryAgent->phone) ?></a>
                            </div>
                        </div>
                    <?php endif ?>
                <?php endif ?>
			</div>
		</div>
	</div>
</div>
