<div class="container grey padding-bottom justified">

    <div class="row margin-top">
        <div class="col-xs-12">
            <h3 class="grey">ACT 273</h3>
        </div>
    </div>

    <div class="row padding-bottom margin-top">
        <div class="col-xs-12 col-sm-12">
            <strong>Purpose</strong>

            <br /><br />

            <p>
                Puerto Rico adopted the “International Financial Center Regulatory Act” (Act 273) to expand Puerto Rico as an international financial center and promote economic growth by broadening the scope of banking activities for international financial entities (IFEs) organized in Puerto Rico as well as additional tax incentives for these IFEs.
            </p>

            <strong>Licensure Requirements</strong>

            <br />

            <p>
                An entity must obtain a license from the Commissioner of Financial Institutions to form an IFE in Puerto Rico. An IFE must be physically located in Puerto Rico, have authorized capital of at least $5,000,000, paid-in capital of at least 250,000, and $300,000 in unencumbered assets or other financial guarantees to obtain licensing, unless a lesser amount is requested by an interested party and approved at the Commissioner’s discretion. The application process requires financial statements of the preceding 10 years of any person who controls or intends to control 10% or more in capital of the proposed IFE. The Commissioner will issue or deny the licensure after an investigation and review of the proposed IFE.
            </p>

            <p>
                A licensed IFE may obtain a Tax Exemption Decree for a term of 15 years, which may be renewed two additional terms. The Tax Exemption Decree constitutes a binding contract between the IFE and the Puerto Rican Government that is immune to any subsequent legislation.
            </p>

            <strong>Permitted IFE Activities</strong>

            <br /><br />

            <p>
                Under Act 273 the following IFE activities are permitted:
            </p>

            <p>
                <ul>
                    <li><span>Accept demand deposits from non-residents of Puerto Rico for commercial purposes or otherwise borrow from other IFEs and non-residents under the Regulations of the Commissioner</span></li>
                    <li><span>Accept adequately collateralized deposits or otherwise borrow money properly secured by the Government Development Bank of Puerto Rico (GDB) and the Economic Development Bank of Puerto Rico (EDB)</span></li>
                    <li><span>Place deposits in any bank or any IFE</span></li>
                    <li><span>Provide loans to any non-resident individuals or entities</span></li>
                    <li><span>Issue or refinance letters of credit for any non-residents and for P.R. residents for financing exports</span></li>
                    <li><span>Invest in securities of the government of P.R.</span></li>
                    <li><span>Engage in foreign currency trade</span></li>
                    <li><span>Trade securities outside of P.R. issued by non-residents</span></li>
                </ul>
            </p>

            <strong>Tax Incentives</strong>

            <br /><br />

            <p>
                IFE incentives:
            </p>

            <p>
                <ul>
                    <li>
                        4% Income Tax on Permitted IFE Activities:
                    </li>
                    <li>
                        0% Property Tax on Real, personal, tangible, and intangible property 
                    </li>
                </ul>
            </p>

            <p>
                IFE Shareholder incentives:
            </p>

            <p>
                <ul>
                    <li>
                        6% Income Tax on Distributions for P.R. residents 
                    </li>
                    <li>
                        0% income Tax on Distributions for non-residents
                    </li>
                </ul>
            </p>

            <br />

            <p>
                <?= $this->partial('card', array('gerente' => $gerente)); ?>
            </p>
        </div>
    </div>
</div>