
<form method='post'>

    <input name='hidden' type='hidden' />

    <h1> <?= t("Do you want to generate models ?"); ?> </h1>
    <p> <?= t("Do you want to generate models dor your current database configuration"); ?> </p>

    <?php if( !empty($message) ) : ?>
        <div class='flash_error'>
            <pre><?= $message; ?></pre>
        </div>
    <?php endif; ?>


    <input name='mode' value='0' type='radio' <?= post('mode' , 0 ) == '0' ? "checked='checked'" : ""  ?>  />
    <label> Make incremental changes </label>    
    <br />

    <input name='mode' value='1' type='radio' <?= post('mode' , 0 ) == '1' ? "checked='checked'" : ""  ?>  />
    <label> Recreate Database and don't load data </label>    
    <br />

    <input name='mode' value='3' type='radio' <?= post('mode', 0 ) == '3' ? "checked='checked'" : ""  ?>  />
    <label> Recreate Database and re-import data </label>    
    <br />

    <input name='mode' value='2' type='radio' <?= post('mode' , 0 ) == '2' ? "checked='checked'" : ""  ?>  />
    <label> Recreate Database and load fixtures </label>    
    <br />
            
    <div class='form_buttons'>
        <button class='button positive'> Generate </button>
        <a href='../' class='button negative'> Cancel </a>
    </div>
    
</form>
